### ISSUE TITLE
There are RT issues

### ISSUE THREAD

**Issue by eserte** [hanfried/File-Random#6]
Please see for example https://rt.cpan.org/Ticket/Display.html?id=123680 --- this problem still happens with the recent 0.20 release.

**Comment by hanfried** [comment]
Thanks for your persistent reporting.

I had a test inside that was checking that 3 random picked lines should be different (what would break if one of the lines would be repicked by random).
With some retrospective (programming was past 20yrs ago), having really random tests on local development is very fine IMHO (it's the best chance to catch some strange errors). But of course for any automatic testing, the tests should be fixed and determinstic.

I now fixed the random seed for this specific test in https://github.com/hanfried/File-Random/commit/d443813897c70cb4dbb82cd22608ff44a958133f - that should solve this issue.
Maybe the better practice would be to fix the seed for all tests. Tbh, I'm a bit out of Perl programming today, so I choosed the easy one liner solution here. If there are any further random breaking tests, I'd investigate how to solve it properly for all tests, but so far I rely on the error report :-o

I uploaded a new version 0.21 to PAUSE/CPAN and will check it in 7-14 days whether the test reports are fine and in case, I'd close this issue.
